# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 11:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_auto_20170314_0633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notification_type',
            new_name='module_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='to_user',
        ),
        migrations.AlterField(
            model_name='notification',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
