# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 12:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_auto_20170321_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlog',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
