# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0007_ownershiprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ownership_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
