# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 04:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0009_auto_20170327_1330'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AlterField(
            model_name='productlog',
            name='past_date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
